name: Publish npm package

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  registry-url: "https://registry.npmjs.org/"
                  # Let setup-node handle auth automatically
                  always-auth: true
                  scope: "@warpy-auth-sdk"

            - name: Install dependencies
              run: npm ci

            - name: Publish package
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
