name: Publish npm package

on:
    release:
        types: [created] # Trigger when a new release is created

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            # 1. Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # 2. Set up Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  registry-url: "https://registry.npmjs.org/"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # 3. Authenticate npm
            - name: Authenticate npm
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            # 4. Install dependencies (optional)
            - name: Install dependencies
              run: npm ci

            # 5. Publish the package
            - name: Publish package
              run: npm publish --access public
